name: deploy

on:
  pull_request:
    types: [ closed ]

jobs:
  up-serve:
    if: github.event.pull_request.merged == true
    name: up
    runs-on: self-hosted
    steps:
    - name: pull and up serve
      run: cd ~/testrepo | git pull | docker-compose down | docker-compose up -d --build


