name: deploy

on: [push]

jobs:
  pylint:
    name: up
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Analysing the code with pylint
      run: cd ~/testrepo | git pull | docker-compose up -d --build


