name: deploy

on: [push]

jobs:
  pylint:
    name: up
    runs-on: self-hosted
    steps:
    - name: pull and up serve
      run: cd ~/testrepo | git pull | docker-compose down | docker-compose up -d --build


